### PR TITLE
Add obsoleted DCNC tags to language registry

### LINKED ISSUE #147: Obsolete Language Codes Registry
Not sure if it's worth. I would share a json of Obsolete Language Codes Registry, which was transcoded from https://www.isdcf.com/site/dcnc-appendix-1c-obsolete-legacy-codes/

I couldn't find any legend about red-colored items. So they are just ignored.

If it's worth, feel free to modify and share it.

{
  "data": [
    {
      "dcncLanguage": "ALBANIAN",
      "dcncTag": "ALB",
      "obsolete": true,
      "obsoletedBy": "SQ"
    },
    {
      "dcncLanguage": "ARABIC",
      "dcncTag": "ARA",
      "obsolete": true,
      "obsoletedBy": "AR"
    },
    {
      "dcncLanguage": "BOSNIAN",
      "dcncTag": "BOS",
      "obsolete": true,
      "obsoletedBy": "BS"
    },
    {
      "dcncLanguage": "BULGARIAN",
      "dcncTag": "BUL",
      "obsolete": true,
      "obsoletedBy": "BG"
    },
    {
      "dcncLanguage": "CATALAN",
      "dcncTag": "CAT",
      "obsolete": true,
      "obsoletedBy": "CA"
    },
    {
      "dcncLanguage": "CZECH",
      "dcncTag": "CES",
      "obsolete": true,
      "obsoletedBy": "CS"
    },
    {
      "dcncLanguage": "CZECH",
      "dcncTag": "CZE",
      "obsolete": true,
      "obsoletedBy": "CS"
    },
    {
      "dcncLanguage": "DANISH",
      "dcncTag": "DAN",
      "obsolete": true,
      "obsoletedBy": "DA"
    },
    {
      "dcncLanguage": "GERMAN",
      "dcncTag": "DEU",
      "obsolete": true,
      "obsoletedBy": "DE"
    },
    {
      "dcncLanguage": "DUTCH",
      "dcncTag": "DUT",
      "obsolete": true,
      "obsoletedBy": "NL"
    },
    {
      "dcncLanguage": "GREEK",
      "dcncTag": "ELL",
      "obsolete": true,
      "obsoletedBy": "EL"
    },
    {
      "dcncLanguage": "ENGLISH",
      "dcncTag": "ENG",
      "obsolete": true,
      "obsoletedBy": "EN"
    },
    {
      "dcncLanguage": "ESTONIAN",
      "dcncTag": "EST",
      "obsolete": true,
      "obsoletedBy": "ET"
    },
    {
      "dcncLanguage": "FINNISH",
      "dcncTag": "FIN",
      "obsolete": true,
      "obsoletedBy": "FI"
    },
    {
      "dcncLanguage": "FRENCH",
      "dcncTag": "FRA",
      "obsolete": true,
      "obsoletedBy": "FR"
    },
    {
      "dcncLanguage": "FRENCH",
      "dcncTag": "FRE",
      "obsolete": true,
      "obsoletedBy": "FR"
    },
    {
      "dcncLanguage": "GERMAN",
      "dcncTag": "GER",
      "obsolete": true,
      "obsoletedBy": "DE"
    },
    {
      "dcncLanguage": "GREEK",
      "dcncTag": "GRE",
      "obsolete": true,
      "obsoletedBy": "EL"
    },
    {
      "dcncLanguage": "HEBREW",
      "dcncTag": "HEB",
      "obsolete": true,
      "obsoletedBy": "HE"
    },
    {
      "dcncLanguage": "HINDI",
      "dcncTag": "HIN",
      "obsolete": true,
      "obsoletedBy": "HI"
    },
    {
      "dcncLanguage": "CROATIAN",
      "dcncTag": "HRV",
      "obsolete": true,
      "obsoletedBy": "HR"
    },
    {
      "dcncLanguage": "HUNGARIAN",
      "dcncTag": "HUN",
      "obsolete": true,
      "obsoletedBy": "HU"
    },
    {
      "dcncLanguage": "ICELANDIC",
      "dcncTag": "ICE",
      "obsolete": true,
      "obsoletedBy": "IS"
    },
    {
      "dcncLanguage": "ICELANDIC",
      "dcncTag": "ISL",
      "obsolete": true,
      "obsoletedBy": "IS"
    },
    {
      "dcncLanguage": "ITALIAN",
      "dcncTag": "ITA",
      "obsolete": true,
      "obsoletedBy": "IT"
    },
    {
      "dcncLanguage": "JAPANESE",
      "dcncTag": "JPN",
      "obsolete": true,
      "obsoletedBy": "JA"
    },
    {
      "dcncLanguage": "KOREAN",
      "dcncTag": "KOR",
      "obsolete": true,
      "obsoletedBy": "KO"
    },
    {
      "dcncLanguage": "LATVIAN",
      "dcncTag": "LAV",
      "obsolete": true,
      "obsoletedBy": "LV"
    },
    {
      "dcncLanguage": "LITHUANIAN",
      "dcncTag": "LIT",
      "obsolete": true,
      "obsoletedBy": "LT"
    },
    {
      "dcncLanguage": "DUTCH",
      "dcncTag": "NLD",
      "obsolete": true,
      "obsoletedBy": "NL"
    },
    {
      "dcncLanguage": "NORWEGIAN",
      "dcncTag": "NOR",
      "obsolete": true,
      "obsoletedBy": "NO"
    },
    {
      "dcncLanguage": "POLISH",
      "dcncTag": "POL",
      "obsolete": true,
      "obsoletedBy": "PL"
    },
    {
      "dcncLanguage": "SPANISH – CASTILIAN",
      "dcncTag": "POR",
      "obsolete": true,
      "obsoletedBy": "ES"
    },
    {
      "dcncLanguage": "ROMANIAN",
      "dcncTag": "RON",
      "obsolete": true,
      "obsoletedBy": "RO"
    },
    {
      "dcncLanguage": "ROMANIAN",
      "dcncTag": "RUM",
      "obsolete": true,
      "obsoletedBy": "RO"
    },
    {
      "dcncLanguage": "RUSSIAN",
      "dcncTag": "RUS",
      "obsolete": true,
      "obsoletedBy": "RU"
    },
    {
      "dcncLanguage": "SERBIAN",
      "dcncTag": "SCC",
      "obsolete": true,
      "obsoletedBy": "SR"
    },
    {
      "dcncLanguage": "CROATIAN",
      "dcncTag": "SCR",
      "obsolete": true,
      "obsoletedBy": "HR"
    },
    {
      "dcncLanguage": "SLOVAK",
      "dcncTag": "SLK",
      "obsolete": true,
      "obsoletedBy": "SK"
    },
    {
      "dcncLanguage": "SLOVAK",
      "dcncTag": "SLO",
      "obsolete": true,
      "obsoletedBy": "SK"
    },
    {
      "dcncLanguage": "SLOVENIAN",
      "dcncTag": "SLV",
      "obsolete": true,
      "obsoletedBy": "SL"
    },
    {
      "dcncLanguage": "PORTUGUESE – EUROPEAN",
      "dcncTag": "SPA",
      "obsolete": true,
      "obsoletedBy": "PT"
    },
    {
      "dcncLanguage": "ALBANIAN",
      "dcncTag": "SQI",
      "obsolete": true,
      "obsoletedBy": "SQ"
    },
    {
      "dcncLanguage": "SERBIAN",
      "dcncTag": "SRP",
      "obsolete": true,
      "obsoletedBy": "SR"
    },
    {
      "dcncLanguage": "SWEDISH",
      "dcncTag": "SWE",
      "obsolete": true,
      "obsoletedBy": "SV"
    },
    {
      "dcncLanguage": "TAMIL",
      "dcncTag": "TAM",
      "obsolete": true,
      "obsoletedBy": "TA"
    },
    {
      "dcncLanguage": "TELUGU",
      "dcncTag": "TEL",
      "obsolete": true,
      "obsoletedBy": "TE"
    },
    {
      "dcncLanguage": "THAI",
      "dcncTag": "THA",
      "obsolete": true,
      "obsoletedBy": "TH"
    },
    {
      "dcncLanguage": "TURKISH",
      "dcncTag": "TUR",
      "obsolete": true,
      "obsoletedBy": "TR"
    },
    {
      "dcncLanguage": "UKRAINIAN",
      "dcncTag": "UKR",
      "obsolete": true,
      "obsoletedBy": "UK"
    },
    {
      "dcncLanguage": "VIETNAMESE",
      "dcncTag": "VIE",
      "obsolete": true,
      "obsoletedBy": "VI"
    }
  ]
}

### PR DESCRIPTION
**Pull request by palemieux**
Improve language registry schema and rev to 1.0.0

Closes #147

### CODE REVIEW

**Review by SteveLLamb — COMMENTED** [review]
Might be a good idea to iterate the schema $id from 1.0.0-beta.2 to 1.0.0-beta.3 with this change.

**Comment by palemieux** [comment]
> Might be a good idea to iterate the schema $id from 1.0.0-beta.2 to 1.0.0-beta.3 with this change.

I think we are going to go `1.0.0`

**Review by SteveLLamb — APPROVED** [review]

**Comment by palemieux** [comment]
@radford-for-smpte Ok to proceed with schema rev?

**Review by ygonno — APPROVED** [review]

**Comment by radford-for-smpte** [comment]
> @radford-for-smpte Ok to proceed with schema rev?

Yep makes sense to me.

**Pull request merged**
