### PR TITLE
Add DIAP - Diaphana - Update studios.json

### PR DESCRIPTION
**Pull request by japierce1028**
Opt OUT (Deluxe Entry)

### CODE REVIEW

**Review by palemieux — APPROVED** [review]

**Review by palemieux — CHANGES_REQUESTED** [review]
@SteveLLamb @japierce1028 Are those records merely entered by Deluxe as courtesy to the underlying studio, or is Deluxe acting as an agent/proxy for the studio?

**Comment by SteveLLamb** [comment]
@palemieux We have many (indie) clients that flat out refuse to fill out the form and ask us to do on their behalf. This is occurring more and more as we have opted for not using `INDI` for all "unknown" studios (for billing and automation purposes), and as more 3rd party vendors are sending us DCPs for versioning that have been created with their own codes, without any regard for the DCNC lists.

**Comment by palemieux** [comment]
@SteveLLamb Can you confirm that Deluxe has the registrant's permission?

**Comment by SteveLLamb** [comment]
Verified Deluxe entered, requested per Studio contact(s).

**Review by palemieux — APPROVED** [review]

**Pull request merged**
