### PR TITLE
Add F1J - Les Films d'un Jour

### PR DESCRIPTION
**Pull request by japierce1028**
Opt IN

### CODE REVIEW

**Review by palemieux — APPROVED** [review]

**Review by palemieux — CHANGES_REQUESTED** [review]
ZIPCODE is missing

**Comment by palemieux** [comment]
@japierce1028 Can you check if the request included a zip code?

**Comment by japierce1028** [comment]
It was not included on their submission. If I go to Google Maps it lists as: 89 Rue Barrault, 75013 Paris, France - should we add the zip? I'm good for not changing their submission. (That being said, I normally add USA to addresses from the states.)

**Comment by palemieux** [comment]
Let's ignore it

**Review by palemieux — APPROVED** [review]

**Pull request merged**
