### PR TITLE
languages: remove audio usage from script entries

### LINKED ISSUE #424: languages: remove audio usage from script-only entries
See #423

> Language tags with a script tag explictly specified should only be used for text purposes (picture / subtitles)

For example, "az-Cyrl" is "az" language written in Cyrillic alphabet (script). It should be used for subtitle.
For its corresponding audio track, "az" is enough.

Since the list is messed up with territory and script names, especially with my recent PR about Chinese, I have a suggestion for you to disscus in next meetings:
* modify description to include "text", e. g. "Tajik - Cyrillic _text_" for "tg-Cyrl"
* remove "audio/subtitles only" usage notes as they're already clear in "_use_"s

### PR DESCRIPTION
**Pull request by xslidian**
Language tags with a script tag explictly specified should only be used for text purposes (picture / subtitles)

Closes #424

### CODE REVIEW

**Comment by palemieux** [comment]
@xslidian Thanks for the PR! Can you create a matching issue? Thanks!

**Comment by palemieux** [comment]
@xslidian @SteveLLamb Per this PR, we would have:

* `az`:  "audio" and "text"
* `az-Cyrl`: "text"
* `az-Latn`: "text"

Shouldn't `az` be "audio" only? Why would someone use `az` for text if `az-Cyrl` and `az-Latn` exist?

**Comment by SteveLLamb** [comment]
> @xslidian @SteveLLamb Per this PR, we would have:

> az: "audio" and "text"
> az-Cyrl: "text"
> az-Latn: "text"
> Shouldn't az be "audio" only? Why would someone use az for text if az-Cyrl and az-Latn exist?

So, easy answer... absence of the script subtag doesn't mean it's audio only. The script is not present if the script is the "default" (used normally in writing and speaking), which can be different per territory. Using `az` as the example, the default is `Arabic` so the `Arab` script subtag is not present. All non-script sub tags are on purpose and have been vetted for both audio and subs, by the territory subtags. In `Azerbaijan` you would just use `az`, but it you used that same language in Russia, it would be `az-Cryl`, with optional `RU` as the end (in this case, we don't use the region subtags unless needed). 

Another way to put this, we don't put `Latn` on `en`, as it's assumed using Latin characters, and just `en` is both audio and text.

**Comment by SteveLLamb** [comment]
This PR should be cancelled, these uses were on purpose, this was not an accident, as described in my comment above.

**Comment by xslidian** [comment]
> The script is not present if the script is the "default" (used normally in writing and speaking), which can be different per territory.

I agree with this logic. 
That's why [I casually added "text" for `NAN` in my earlier PR](https://github.com/ISDCF/registries/pull/380/commits/ff84b55550bd8fa7970cb62565ed8b74e593704e#diff-581bb054dabb1c77650b70cb89a979a1384aeec6fa7431e47926c45ea12a0786R596) (reverted by Steve later, as the limitation was inherited from the very early DCNC language table).

I suggest adding "text" for `QMN` and `NAN`, as `YUE` has it -- this is a significant change and need to be decided at your member meetings.

**Comment by SteveLLamb** [comment]
> That's why [I casually added "text" for `NAN` in my earlier PR](https://github.com/ISDCF/registries/pull/380/commits/ff84b55550bd8fa7970cb62565ed8b74e593704e#diff-581bb054dabb1c77650b70cb89a979a1384aeec6fa7431e47926c45ea12a0786R596) (reverted by Steve later, as the limitation was inherited from the very early DCNC language table).

So this is one we actually service a LOT. `nan` is used for only spoken, while for the same region(s) text/subs we use `"ZSTW" "zh-Hans-TW"` or `"QMT" "cmn-Hant"` . This is how the territory prefers.

Thanks for helping untangle all this btw!

**Comment by xslidian** [comment]
> `nan` is used for only spoken, while for the same region(s) text/subs we use `"ZSTW" "zh-Hans-TW"` or `"QMT" "cmn-Hant"` . This is how the territory prefers.

Yes, Mandarin subtitle is preferred in theatrical releases, as it’s the "national language" and allow people who don't understand `nan` (i.e. _Taiwanese_) to watch together with others.

But `NAN` can actually be written in Han characters! Here's a example with burned-in `nan-Hant` subtitle: https://www.youtube.com/watch?v=GTXPdi5Jhlo
Younger people prefer the Latin transliteration `nan-Latn` and they wrote https://zh-min-nan.wikipedia.org/

On the mainland side, we have lots of tv series dubbed in `nan`, but like your TW clients, we lazily sub them in Mandarin :D

**Comment by SteveLLamb** [comment]
> But NAN can actually be written in Han characters! Here's a example with burned-in nan-Hant subtitle: https://www.youtube.com/watch?v=GTXPdi5Jhlo
Younger people prefer the Latin transliteration nan-Latn and they wrote https://zh-min-nan.wikipedia.org/

Oh boy, thanks for those examples! So for those we can make another "language" instance for the sub only versions (`nan-Hant` and `nan-Latn`) later, if needed, which will keep the current `nan` as audio only. We currently don't service these sub versions in Cinema, which is why I didn't add.

**Pull request merged**
