### PR TITLE
Added Facilities (CBZ, OND) closes #30

### LINKED ISSUE #30: Add Facilities: CBZ OND
CBZ
OND

See Google sheet (facilities) responses

### PR DESCRIPTION
**Pull request by SteveLLamb**
Worked this issue and branch via GitHub site directly to train Jerry.

### CODE REVIEW

**Comment by SteveLLamb** [comment]
Jerry to chat with Pierre - Maybe only Mike, Pierre, Steve should make updates (using GitHub site directly may not work)

**Comment by palemieux** [comment]
>     "code": "OND",

This is out of order, and should come before `ONE`

**Comment by SteveLLamb** [comment]
> > ```
> > "code": "OND",
> > ```
> 
> This is out of order, and should come before `ONE`

The page reorders based on codes prior to rendering from the template. Is this super important?

**Comment by palemieux** [comment]
> > > ```
> > > "code": "OND",
> > > ```
> > 
> > 
> > This is out of order, and should come before `ONE`
> 
> The page reorders based on codes prior to rendering from the template. Is this super important?

Yes, it ensures that there is a canonical representation of the data.

**Comment by palemieux** [comment]
Replaced by #34 and #35

**Pull request closed without merging**
