### PR TITLE
Normalize Chinese entries & add regional 4-letter DCNC tags

### LINKED ISSUE #421: Normalize Chinese entries & add regional 4-letter DCNC tags
See https://github.com/ISDCF/registries/pull/380

### LINKED ISSUE #422: CMN and NAN were audio-only in Digital-Cinema-Language-Codes-Archive-20200924 and before March.
See https://github.com/ISDCF/registries/pull/380

### PR DESCRIPTION
**Pull request by xslidian**
`Hans` & `Hant` entries should always be picture-and-text-only.

Description is made up in this order: 
`cmn-Hans-SG` => `zh-cmn-Hans-SG` => Chinese (`zh`) - Mandarin (`cmn`) - Han Simplified variant (`Hans`) - Singapore (`SG`)

I'm only adding missing 4-letter tags that are non-controversial and easy to construct (`ZSxx` & `ZTxx`).

Other frequently used but missing candidates aren't included in this PR, like:

- `cmn-CN` - Chinese, Mandarin, China mainland (re-dubbed Mandarin audio, different from the original Mandarin audio)
- `nan-TW` - Chinese, Min Nan, Taiwan (this is what people actually call _Taiwanese_ in real life, but not recommend as critics say it weakens other dialects' position in Taiwan; studios simply use `NAN` right now)

Closes #421 
Closes #422

### CODE REVIEW

**Comment by SteveLLamb** [comment]
@xslidian This is SUPER helpful. I have pushed a commit to re-sort so it passes our validation. I will review over the next week. Thanks!

**Comment by xslidian** [comment]
They aren't frequently used. Just take it easy. :D

I just added some more regional `CSxx` & `CTxx` tags (all _written_ forms) following your existing [`CSSG`](https://github.com/ISDCF/registries/blame/dcd6a0c57ae99f257f9fe3d60f160f58094c3861/src/main/data/languages.json#L495) style. 
The only existing DCNC tags starting with `CS` & `CT` are `CS` (Czech) and `CSSG` (`cmn-Hans-SG`).

It's up to you to decide tag forms for the `cmn-CN` & `nan-TW` _spoken_ series :P

**Comment by xslidian** [comment]
Note that `CMN` and `NAN` were _audio_-only in [Digital-Cinema-Language-Codes-Archive-20200924](https://www.isdcf.com/site/wp-content/uploads/2020/09/Digital-Cinema-Language-Codes-Archive-20200924.pdf) and [before March](https://github.com/ISDCF/registries/blame/888b74db17f91be66878dc704af312faf9855679/src/main/data/languages.json).

`CMN` became [_"audio" & "text"_](https://github.com/ISDCF/registries/blame/5668523e6ce916d63ab2bb4975cddd2ed03c0b23/src/main/data/languages.json) in your [dcd6a0c](https://github.com/ISDCF/registries/commit/dcd6a0c57ae99f257f9fe3d60f160f58094c3861) (#342).

In this PR, I updated `NAN` (Min Nan Chinese) with _"text"_ (matching `CMN`'s) because the language do have multiple writing systems (in <abbr title="Han characters">Hani</abbr>, <abbr title=Bopomofo>Bopo</abbr>, <abbr title=Latin>Latn</abbr>, <abbr title=Hangul>Hang</abbr> or <abbr title=Katakana>Kana</abbr> syllabaries) besides the commonly-seen translated subtitles in Mandarin vocabulary. 
The [Min Nan Wikipedia](https://zh-min-nan.wikipedia.org/) is written in _Pe̍h-ōe-jī_ (literally _vernacular writing_) which can be tagged as `nan-Latn` (BCP 47 style) or `zh-nan-Latn` (extlang style).
`nan-Hanb` is used more frequently in formal subtitles.

It may constitute a significant change and you may want to remove the two <em>"text"</em>s before merging and discus at the next meeting (also #381 which changes territory names).

**Review by SteveLLamb — APPROVED** [review]

**Comment by palemieux** [comment]
@xslidian A quick review of the revised PR would be appreciated. Any remaining issues in your mind?

**Comment by xslidian** [comment]
It looks good to me to get officially published.
I added two notes so they're equivalent to the [20200924](https://www.isdcf.com/site/wp-content/uploads/2020/09/Digital-Cinema-Language-Codes-Archive-20200924.pdf) revision.

I started this PR mainly to fix obvious typos (e.g.  [the _text_-only tag `zh-Hant-MY` became _audio_-only](https://github.com/ISDCF/registries/commit/5ae069a706f7fa4be3e84e77e52a26d90088fa8f#diff-581bb054dabb1c77650b70cb89a979a1384aeec6fa7431e47926c45ea12a0786R596)). 
We can talk about `use`s for `CMN`, `NAN` and [`YUE` (audio & text)](https://github.com/ISDCF/registries/blob/4bbc4c99ad30ae70446dda2f9ebadcdd8332e2a2/src/main/data/languages.json#L461) later.

**Pull request merged**
