### PR TITLE
fix case in scope for Dolby EDR

### PR DESCRIPTION
**Pull request by dcbullock**
change EDR-metada to EDR-Metadata

fixes https://github.com/ISDCF/registries/issues/444

### CODE REVIEW

**Review by radford-for-smpte — APPROVED** [review]

**Comment by dcbullock** [comment]
Hi.  I may have made an error with GitHub here.  I meant to do two PRs, one for the case fix, and a second one to update the contact information.  It looks like both changes were scooped up in this PR and the contact update was added after Mike did the review.  It's fine with me if both changes are merged at the same time.

Who does the merge?

**Comment by palemieux** [comment]
The creator of the PR should do the merge unless they do not have permission to do.

The creator of the PR should not create the PR until it is ready to merge.

The creator of the PR should request a review.

**Comment by radford-for-smpte** [comment]
> 
> The creator of the PR should not create the PR until it is ready to merge.
> 

It’s common to have PRs for work not ready to merge. In those cases they should just be flagged as “draft”.

**Comment by dcbullock** [comment]
permission:  I don't think I have permission to merge - but will look more closely for a merge button.
review request:  i know that now - i did that for the SMPTE/html-pub (thank you, Mike, for noticing my PR here)
PR when ready to merge:
Yes, that is what I did.
* I made the PR after I committed dcbullock/isdcf-registries (my fork of ISDCF/registries) - I was ready.
* Then I made another commit to the same branch to dcbullock/isdcf-registries.  That commit is now in the original PR.
I did not think that I should have keep the branch frozen until after the PR was merged.  Now I know.


*

**Comment by dcbullock** [comment]
I don't see a "Merge" button anywhere on my view of the PR.

**Comment by dcbullock** [comment]
If desired, I am happy to close the PR without merging, and start again.  That would keep things clean.

**Comment by SteveLLamb** [comment]
> I have no idea if the CI tooling ran again after I made the second commit that ended up in the PR. Did it?

Yes, it completed fine, you would see this at the very bottom of this page:
Screen Shot 2022-08-25 at 10 29 08 AM

> If desired, I am happy to close the PR without merging, and start again. That would keep things clean.

Nah, let's get you the correct perms. @palemieux @radford-for-smpte, can you give Dean write access?

**Comment by dcbullock** [comment]
@SteveLLamb that "all green" tooling indication was in place _before_ I made the second commit.  So as far as I can tell the order was:

1) commit the fix for the case error
2) create new PR dcbullock/isdcf-registries -> ISDCF/registries
3) tooling ran and all turned green
4) Mike reviewed and approved the PR
5) I looked to see if I could merge and learned that I could not
6) I decided to go ahead an do another commit to dbullock/isdcf-registries to change contact info
7) the commit to change contact info ended up in the PR
8) the tooling remained green and Mike's approval remained in place

Se we ended up with a PR that was CI checked and human reviewed and approved with an extra commit that was not human reviewed and possibly not CI checked.

Granted, I now know to not add commits to a branch that has a pending PR unless the PR is a "draft" PR.  Am I mistaken about the flow?  I am surprised that an existing PR that is not in "draft" mode would pick up extra commits after the PR is created and especially after the PR is CI checked and human approved.  

Am I missing something?  I am very new to GitHub workflows.  Most of my git experience is command line with ssh remote repos - no PRs, and a bit with GitLab workflow.

**Review by SteveLLamb — APPROVED** [review]

**Comment by SteveLLamb** [comment]
> Se we ended up with a PR that was CI checked and human reviewed and approved with an extra commit that was not human reviewed and possibly not CI checked.
> Granted, I now know to not add commits to a branch that has a pending PR unless the PR is a "draft" PR. Am I mistaken about the flow? I am surprised that an existing PR that is not in "draft" mode would pick up extra commits after the PR is created and especially after the PR is CI checked and human approved

@dcbullock Ah, I understand now. 

So generally, we have the checks set up for all commits, it will auto run the CI check for any commit to a PR, no matter the state. You can also go to `show all checks` and trigger a re-run of the check at any time you like (but's it unnecessary, I did that just now, and it's fine). You not need worry about it being CI checked, it will every time (unless something breaks).

We add commits all the time to an open PR, to make updates as requested, or one of us has a suggestion. or other reasons. We're managing it by just requested another review if you do another commit, which is how we're saying it's "ready" for review. I have approved all changes on this PR now, so you're good on all fronts with this PR. If you still don't see the squash and merge, I'm happy to do it for you until we sort our your perms.

**Pull request merged**
