### PR TITLE
Confirm that studios and facilities have consistent contact information

### LINKED ISSUE #597: Confirm that studios and facilities with the same code have consistent contact information
Should studios and facilities that have the same code have consistent contact information?

Are there studios and facilities with the same code but completely different organization?

See https://github.com/ISDCF/registries/pull/594 as an example.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #597

### CODE REVIEW

**Comment by palemieux** [comment]
@japierce1028 The following facilities and studios have inconsistent contact information:

- [ ] 123
- [ ] ALT
- [ ] AST
- [ ] AVC
- [ ] BA
- [ ] BGP
- [ ] CFP
- [ ] CRL
- [ ] CSC
- [ ] CZN
- [ ] DA
- [ ] DS
- [ ] EFS
- [ ] EYW
- [ ] FOS
- [ ] FYM
- [ ] GCS
- [ ] GMF
- [ ] IRL
- [ ] JOP
- [ ] JRM
- [ ] LC
- [ ] LEO
- [ ] LF
- [ ] MAD
- [ ] NP
- [ ] O2
- [ ] PP
- [ ] PRL
- [ ] PSP
- [ ] S4U
- [ ] SC
- [ ] SDM
- [ ] SF
- [ ] SNP
- [ ] SWF
- [ ] TFL
- [ ] TK
- [ ] TVC
- [ ] VPS
- [ ] XVS

**Comment by japierce1028** [comment]
That is a long list. I'm tempted to have exceptions for all existing conflicts and require it going forward only.

**Comment by palemieux** [comment]
I recommend we at least glance through the list to make sure there is nothing terrible/obvious.

**Comment by palemieux** [comment]
… and maybe an issue for each one so we can fix over time

**Comment by japierce1028** [comment]
I think it would be OK to have an issue for each one. Just don't have the energy to do a detailed study to fix the existing ones.

**Pull request closed without merging**
