### PR TITLE
Update ADHP

### PR DESCRIPTION
**Pull request by japierce1028**
Email request to remove address on this listing. (I have asked about his name/email.)

### CODE REVIEW

**Comment by palemieux** [comment]
@japierce1028 @SteveLLamb Currently we require name, email and address, if contact information is provided. Should we instead require name and at least one of email and address?

**Comment by japierce1028** [comment]
I certainly think that there is no requirement for either email or address. All the legacy facilities/studios have no contact info.

**Comment by palemieux** [comment]
Does it make sense to have a _name_ without also having at least an _email_ or a _physical address_? [ed.: I do not think so.]

**Comment by palemieux** [comment]
See https://github.com/ISDCF/registries/pull/545, which proposed relaxing the requirements for both email and address to be present.

**Review by palemieux — APPROVED** [review]

**Pull request merged**
