### PR TITLE
Updated CMQ contact info

### LINKED ISSUE #83: Update Facility - CMQ
User requested updated contact info be added.

### PR DESCRIPTION
**Pull request by SteveLLamb**
Closes #83

### CODE REVIEW

**Comment by palemieux** [comment]
@SteveLLamb `"url": ""` ?

**Comment by SteveLLamb** [comment]
> @SteveLLamb `"url": ""` ?

No, extra comma in content, has been fixed.

**Review by palemieux — CHANGES_REQUESTED** [review]
The empty string is not a valid URL.

**Comment by SteveLLamb** [comment]
> The empty string is not a valid URL.

Where are you seeing that? This was updated:

    "code": "CMQ",
    "description": "CINEMATIQ"	    "contact": {
      "address": "2180 Bryant St, Suite 210, San Francisco, CA 94110",
      "email": "info@cinematiq.com",
      "name": "Paul Scolieri"
    },
    "description": "CINEMATIQ",
    "url": "https://cinematiq.com"

**Review by palemieux — APPROVED** [review]

**Pull request merged**
