### PR TITLE
Add RK / Obsolete LUM - Regular Kolor - Update facilities.json

### PR DESCRIPTION
**Pull request by japierce1028**
Opt IN, request to obsolete LUM

### CODE REVIEW

**Comment by palemieux** [comment]
@japierce1028 How did we confirm this obsoleted LUM?

**Review by palemieux — CHANGES_REQUESTED** [review]
How do we verify that the party requesting obsolescence is authorized to do so? In the meantime, we could split this into two PRs.

**Comment by palemieux** [comment]
I would deprecate `LUM` but not link `RK` to `LUM` to since it is a completely different company.

**Comment by japierce1028** [comment]
But the email says it IS the same company, just different owners.

**Comment by palemieux** [comment]
> It's the same company, but the owners have changed (and the name too).

Oh. I misread the email. Thanks.

**Review by palemieux — APPROVED** [review]

**Pull request merged**
