### PR TITLE
Add LCB - Laboratório de Imagem e Som - Cinemateca Brasileira

### PR DESCRIPTION
**Pull request by japierce1028**
Out OUT

### CODE REVIEW

**Comment by japierce1028** [comment]
I mistakenly added SND - a studio to this branch in addition to the LCB facility. Is it worth pulling it out and submitting a separate pull request?

**Comment by SteveLLamb** [comment]
> I mistakenly added SND - a studio to this branch in addition to the LCB facility. Is it worth pulling it out and submitting a separate pull request?

@japierce1028 yes, for consistency sake, please do.

**Review by palemieux — CHANGES_REQUESTED** [review]
Just a reminder to split this pull request

**Comment by japierce1028** [comment]
A reminder would have been appropriate if someone had responded when I asked if I SHOULD split it. I heard nothing so assumed it was fine. But now that you are (I think) asking for me to remove it, it's done.

**Review by palemieux — APPROVED** [review]

**Pull request merged**
