### PR TITLE
Obsolete EM - replaced by CH

### PR DESCRIPTION
**Pull request by japierce1028**
Will send email to confirm with facility.

### CODE REVIEW

**Comment by japierce1028** [comment]
I'm guessing it won't confirm since CH doesn't exist (yet). Right?

**Review by palemieux — APPROVED** [review]

**Comment by palemieux** [comment]
@japierce1028 Are we good to merge?

**Comment by japierce1028** [comment]
Let's wait to hear back from my request for more info. I give it 98% chance that all is OK, but worth waiting.

**Comment by palemieux** [comment]
@japierce1028 Good to merge?

**Comment by japierce1028** [comment]
I have not heard back. I would not merge.

**Review by palemieux — CHANGES_REQUESTED** [review]
WIP

**Comment by japierce1028** [comment]
We got a reply. Looks like we are good to go...

My apologies Jerry. I completely missed this!

My original post-production company was called Etch Media, but I felt I should have the word “post” in the name, so it didn’t sound like a multi-media company. So, I opened a new company called Chroma Post. Etch Media is still incorporated and operating, but I don’t run any post-production through it - it’s now a VAR.

Hopefully that makes sense.

Thank you for all that you do in keeping this organized, and doing some due diligence - it’s very much appreciated.


CHROMA POST
ROB NEILSON / +1 (604) 719-6754
WWW.CHROMAPOST.IO

**Review by palemieux — APPROVED** [review]

**Pull request merged**
